host: 0.0.0.0
port: 3000

# not implemented yet
# ssl:
#   enable: false
#   crtpath: ssl/server.crt
#   keypath: ssl/server.key

clean_files_on_start: false

commands:
  python:
    - pyls
    - -v
  cpp:
    - ccls
    - >
      --init={
          "capabilities": {
            "foldingRangeProvider":false
          },
          "index":{
            "onChange":true,
            "trackDependency":2
          }
        }
  # cpp:
  #   - clangd
