host: 0.0.0.0
port: 3000

ssl:
  enable: false
  crtpath: ssl/server.crt
  keypath: ssl/server.key

commands:
  python:
    - pyls
    - -v
  cpp:
    - ccls
    - >
      --init={
        "capabilities": {"foldingRangeProvider":false},
        "index":{"onChange":true,"trackDependency":2},
        "clang":{
          "resourceDir":"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6"
          }
        }
  # cpp:
  #   - clangd
